//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 8 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `c070615`.
    var c070615: RswiftResources.ColorResource { .init(name: "c070615", path: [], bundle: bundle) }

    /// Color `c100D2C`.
    var c100D2C: RswiftResources.ColorResource { .init(name: "c100D2C", path: [], bundle: bundle) }

    /// Color `c23175F`.
    var c23175F: RswiftResources.ColorResource { .init(name: "c23175F", path: [], bundle: bundle) }

    /// Color `c525878`.
    var c525878: RswiftResources.ColorResource { .init(name: "c525878", path: [], bundle: bundle) }

    /// Color `c6D59D3`.
    var c6D59D3: RswiftResources.ColorResource { .init(name: "c6D59D3", path: [], bundle: bundle) }

    /// Color `cD92929`.
    var cD92929: RswiftResources.ColorResource { .init(name: "cD92929", path: [], bundle: bundle) }

    /// Color `cFEFFFF`.
    var cFEFFFF: RswiftResources.ColorResource { .init(name: "cFEFFFF", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 15 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `antispyTipsIcon`.
    var antispyTipsIcon: RswiftResources.ImageResource { .init(name: "antispyTipsIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrowImage`.
    var arrowImage: RswiftResources.ImageResource { .init(name: "arrowImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backButtonImage`.
    var backButtonImage: RswiftResources.ImageResource { .init(name: "backButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bluetoothDetectionIcon`.
    var bluetoothDetectionIcon: RswiftResources.ImageResource { .init(name: "bluetoothDetectionIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `deviceBadBackgroundImage`.
    var deviceBadBackgroundImage: RswiftResources.ImageResource { .init(name: "deviceBadBackgroundImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `deviceGoodBackgroundImage`.
    var deviceGoodBackgroundImage: RswiftResources.ImageResource { .init(name: "deviceGoodBackgroundImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `goNextImage`.
    var goNextImage: RswiftResources.ImageResource { .init(name: "goNextImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `infraredScannerIcon`.
    var infraredScannerIcon: RswiftResources.ImageResource { .init(name: "infraredScannerIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `magneticBackgroundImage`.
    var magneticBackgroundImage: RswiftResources.ImageResource { .init(name: "magneticBackgroundImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `magneticDetectionIcon`.
    var magneticDetectionIcon: RswiftResources.ImageResource { .init(name: "magneticDetectionIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mainBackgroundImage`.
    var mainBackgroundImage: RswiftResources.ImageResource { .init(name: "mainBackgroundImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `scaleImage`.
    var scaleImage: RswiftResources.ImageResource { .init(name: "scaleImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settingsImage`.
    var settingsImage: RswiftResources.ImageResource { .init(name: "settingsImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `wifiBadImage`.
    var wifiBadImage: RswiftResources.ImageResource { .init(name: "wifiBadImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `wifiGoodImage`.
    var wifiGoodImage: RswiftResources.ImageResource { .init(name: "wifiGoodImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `scaningAnimation.json`.
    var scaningAnimationJson: RswiftResources.FileResource { .init(name: "scaningAnimation", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }
  }
}